// los mensajes al server pueden ser de TEXTLENGTH_MAX

#define DEBUG_MAX_MEMINFO 256
#define DEBUG_MAX_CONTEXTS 100
#define DEBUG_ENABLED 1

#define USER_MODE_HAS_0 0
#define USER_MODE_HAS_OP 1
#define USER_MODE_HAS_V 2

#define CONFIG_CONNECT_TIMEOUT 10

#define TEXTLENGTH_STD 256
#define TEXTLENGTH_MAX 2048
#define T_ERROR -1
#define T_UNDEF 0
#define T_OK 0
#define T_IGNORE 1

#define SELF_STATUS_UNDEF 0
#define SELF_STATUS_OK 1
#define SELF_STATUS_EXIT 2

#define SERVER_LATENCY_USEC 250000
#define SERVER_LATENCY_SEC 0

#define SERVER_STATUS_NOTCONNECTED 1
// missing mode
#define SERVER_STATUS_CONNECTED_1 2
// fully conected
#define SERVER_STATUS_CONNECTED_2 4
#define SERVER_STATUS_TRYING 8
#define SERVER_STATUS_EXIT 16

#define SERVER_SEND_NOW 1
#define SERVER_SEND_NORMAL 2

#define SERVER_QUEUE_MAXSIZE 100

#define SERVER_WAIT_RECONNECT 10

#define TIMER_QUEUE_SIZE 10
#define TIMER_SERVER_WAIT_RECONNECT 0
#define TIMER_SERVER_EVERY1SEC 1
#define TIMER_SERVER_EVERY20SEC 2

#define OUTPUT_DEST_NO 1
#define OUTPUT_DEST_LOG 2
#define OUTPUT_DEST_CORE 4
#define OUTPUT_TYPE_DEBUG_EXTRA 8
#define OUTPUT_TYPE_DEBUG 16
#define OUTPUT_TYPE_INFO 32
#define OUTPUT_TYPE_WARN 64
#define OUTPUT_TYPE_SQL 128
#define OUTPUT_TYPE_CRITICAL 256

#define MODULE_HOOK_IRCINPUT 1
#define MODULE_HOOK_RETRY 2
#define MODULE_HOOK_EVERY1SEC 4
#define MODULE_HOOK_EVERY20SEC 8
#define MODULE_HOOK_PRIVMSG 16
#define MODULE_HOOK_SERVERQUIT 32
#define MODULE_HOOK_DUMPSTATUS 64
